### ISSUE TITLE
Which specific ImageNet dataset should be used to train, to reproduce the results of your experiments in the paper?

### ISSUE THREAD

**Issue by HyZhu39** [ToTheBeginning/GCP-Colorization#1]
Thank you for your excellent work. I was greatly inspired after reading your paper and wanted to reproduce your experimental results, but I encountered a problem during training. The ImageNet dataset from the official website:
> https://image-net.org/download-images.php

There are a lot of versions to choose from. Which ImageNet subset did you choose for your network?
Since I don't know enough about the ImageNet dataset, this may be a stupid question, thanks, and looking forward to your answer.

**Comment by ToTheBeginning** [comment]
We use ImageNet-1k dataset which contains 1,281,167 training images and 50,000 validation images.
